# This is a basic workflow to help you get started with Actions

name: CI-Download

# Controls when the workflow will run
on:
  schedule:
    - cron:  '*/10 * * * *'
  # Triggers the workflow on push or pull request events but only for the main branch
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
#       - name: Run a one-line script
#         run: wget https://sritez-backup.s3.ap-south-1.amazonaws.com/sritez-prod-ubuntu.zip

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          for (( i = 0; i < 5; i++ )); do
          wget -q https://sritez-backup.s3.ap-south-1.amazonaws.com/sritez-prod-ubuntu.zip 
          du -sh *
          rm -f *.zip 
          done
          echo Add other actions to build,
          echo test, and deploy your project.
